..\manage.py loaddata m2mbench.board01.json
..\manage.py loaddata m2mbench.board02.json
..\manage.py loaddata m2mbench.board03.json
..\manage.py loaddata m2mbench.board04.json
..\manage.py loaddata m2mbench.board05.json
..\manage.py loaddata m2mbench.board06.json
..\manage.py loaddata m2mbench.board07.json
..\manage.py loaddata m2mbench.board08.json
..\manage.py loaddata m2mbench.board09.json
..\manage.py loaddata m2mbench.board10.json
